=== rohan-hulage/WT-Ex_5/student.dtd
<!ELEMENT students (#PCDATA|employee)*>
<!ELEMENT students
(firstname,lastname,roll_no,division)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT roll_no (#PCDATA)>
<!ELEMENT division (#PCDATA)>

=== rohan-hulage/WT-Ex_5/students-dtd.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE employees SYSTEM "student.dtd">
<students>
    <student>
        <firstname>Harshad</firstname>
        <lastname>Pachpute</lastname>
        <roll_no>TCOA43</roll_no>
        <division>Materials</division>
    </student>
    <student>
        <firstname>Abhishek</firstname>
        <lastname>Hulage</lastname>
        <roll_no>TCOA42</roll_no>
        <division>Accts Payable</division>
    </student>
</students>
