=== rohan-hulage/WT-Ex_5/student.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
<xs:element name="students-xsd">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="firstname" type="xs:string" />
      <xs:element name="lastname" type="xs:string" />
      <xs:element name="roll_no" type="xs:string" />
      <xs:element name="division" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== rohan-hulage/WT-Ex_5/students-xsd.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<students-xsd xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="student.xsd">
<students-xsd>
    <student>
        <firstname>Harshad</firstname>
        <lastname>Pachpute</lastname>
        <roll_no>TCOA43</roll_no>
        <division>A</division>
    </student>
    <student>
        <firstname>Abhishek</firstname>
        <lastname>Hulage</lastname>
        <roll_no>TCOA42</roll_no>
        <division>A</division>
    </student>
    <student>
        <firstname>Tom</firstname>
        <lastname>Roland</lastname>
        <roll_no>TCOA03</roll_no>
        <division>A</division>
    </student>
    <student>
        <firstname>Will</firstname>
        <lastname>Gavni</lastname>
        <roll_no>TCOA04</roll_no>
        <division>A</division>
    </student>
</students-xsd>
</students-xsd>
